name: webrtc-proxy
version: git
summary: webrtc-proxy
description: webrtc-proxy

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

plugs:
  network:
  network-bind:

apps:
  webrtc-proxy:
    command: bin/webrtc-proxy -c $SNAP_DATA/config
    daemon: simple

parts:
  webrtc-proxy:
    plugin: rust
    source: .
    build-packages:
      - cargo
      - rustc
      - pkg-config
      - libssl-dev
